### ISSUE TITLE
Configured fonts not always used

### ISSUE THREAD

**Issue by schloram** [maikschneider/bw_captcha#12]
Hi @maikschneider ,
I just realised that you changed [my code for the configurable fonts](https://github.com/itplusx/bw_captcha/blob/c0e636b53585b5318666e8309cb93483531e382c/Classes/Utility/CaptchaBuilderUtility.php#L75). This change has the following impact:

If a user sets multiple fonts inside the `fontFiles` settings but one of them is invalid (maybe because it does not exit) it might fall back to the fonts provided by `gregwar/captcha` lib even though another custom font in the list might be valid.

Expected behavior:  
If at least one custom font is a valid file this file should be used instead of falling back to the `gregwar/captcha` fonts. Fallback should only happen if none of the custom fonts are valid.

How to reproduce:
1. Add two custom fonts via TypoScript `fontFiles` settings.
2. Change one font file to be invalid on purpose (e.g add an additional letter to the filename) so that only one font is valid.
3. Call the form containing a captcha multiple times. You will realise that sometimes none of the custom fonts is being used but it uses the `gregwar/captcha` fonts instead.

At this point I'm wondering why you changed my code that much because I already thought of these cases. Did you encounter errors with it?

Also I've seen that some of your code additions in [CaptchaBuilderUtility.php](https://github.com/maikschneider/bw_captcha/blob/development/Classes/Utility/CaptchaBuilderUtility.php) were not really necessary as my code already covered it:

- With the `retrieveFileOrFolderObject()` and `getFileAbsFileName()` inside the try catch I already covered the `EXT` paths and file storage as well. If you look inside the `retrieveFileOrFolderObject` method they internally check for the "EXT" prefix already. So actually no need to do this beforehand. (=> would make your lines 87-90 redundant)
- With the  `foreach()` around the `try catch` block I iterated over every custom font and only set the `$randomFontFile` when the current font is a valid file. If no valid font is in the list of custom fonts it's `null`. So no check for the existence of the file afterwards is necessary (=> would make your lines 107-109 redundant).  
  This also prevents the above described bug from happening because it will always use the custom fonts if there is at least one valid font in the list. Otherwise it will use the  `gregwar/captcha` fonts.

**Comment by maikschneider** [comment]
Hi @schloram,
I changed your code for a couple of reasons.

* it is not working for TYPO3 v11+: `getFileAbsFileName` doesn't work for public paths anymore
* performance: You loop over every configured font when only one is needed
* `getFileAbsFileName` can return empty string, the check is not redundant

Regarding the error handling: Configuring a wrong file path makes the whole configuration invalid and should be fixed. Ignoring this by using another configured option prevents the user from detecting the issue + it does not justify the cost.

**Comment by schloram** [comment]
Hi @maikschneider,
thanks for your fast response! 👍 Really appreciate it!

Fair enough. Just a few comments:

> it is not working for TYPO3 v11+: `getFileAbsFileName` doesn't work for public paths anymore

It still does. You can still call `GeneralUtility::getFileAbsFileName('fileadmin/user_upload/myfile.txt')` and it returns the correct absolute path.
But something seems to have changed in TYPO3 v11 that in my code an absolute path (with prefixed `/`) is returned by the `retrieveFileOrFolderObject()` method. But you fixed this already [by dumping `getFileAbsFileName` and building the path yourself](https://github.com/maikschneider/bw_captcha/blob/v2.0.2/Classes/Utility/CaptchaBuilderUtility.php#L102). So that's actually better and this is IMHO the only necessary fix to make it compatible with v11+.  
Therefore in my eyes [the "check EXT: path" part](https://github.com/maikschneider/bw_captcha/blob/v2.0.2/Classes/Utility/CaptchaBuilderUtility.php#L92-L96) is still not necessary because already covered by `$resourceFactory->retrieveFileOrFolderObject()`.

> performance: You loop over every configured font when only one is needed

But looping over every font and wrap it in a `try catch` prevents the described bug from happening. So it only returns null (and falls back to the `gregwar/captcha` fonts) if none of the custom fonts works.  
And to be honest: We're talking about a handful of font to be iterated over. It think the whole performance issue can be neglected here.

> getFileAbsFileName can return empty string, the check is not redundant

That's the reason for [my `try catch` block](https://github.com/itplusx/bw_captcha/blob/c0e636b53585b5318666e8309cb93483531e382c/Classes/Utility/CaptchaBuilderUtility.php#L83).  
With this the variable `$randomFontFile` will only be set if the `$resourceFactory->retrieveFileOrFolderObject()` method does not throw an exception. And if you look inside the code of that method you see that if the fontFile given by the user is invalid in any way an exception is thrown. So there will never be an empty string (only `null`) after the `try catch`. This is why I'm of the opinion that the check afterwards has no use.

> Ignoring this by using another configured option prevents the user from detecting the issue
The thing is, that the user is not necessarily noticing it right away because maybe most of the time it uses one of the other 4 fonts. But in one case it uses the other default fonts which seems quite odd.  
If your intention is that the user notices that one font is invalid I would rather write a log entry for it instead of falling back to one of the default fonts.

While I totally agree, that the case where a font file is invalid should almost never occur because as a developer you make sure that the custom fonts you are trying to use are present. But my expectation is if I have let's say 5 custom fonts and only one is invalid (because...I don't know...someone deleted it from the fileadmin) it should never fall back to the default but rather take one of the other 4 valid fonts.


To be honest I feel kinda dumb writing this novel because it's your repo and you can do whatever you like. 😊 But I invested some time to come up with a well thought out solution only to see it being overridden with changes that were (mostly) already covered by my code.

If you still consider this the expected behavior feel free to close this issue then.

kind regards

**Comment by maikschneider** [comment]
Yes. I'm not sure what you are trying to achieve.
* I checked out your PR and it was not working (fact)
* I didn't like the code style (highly subjective, don't mind it)
* I merged your PR, adjusted the code and included more checks (many others would have rejected)
* I tested it in v10, v11 and v12
* I backported it for v9
* I published new releases and explained the reasons for my changes
Sorry, but since the feature you request is working I'm going to close this conversation. I like your passion, please feel free to submit further PRs in the future!
Cheers,
Maik

**Comment by schloram** [comment]
@maikschneider I actually was trying to explain that my code was perfectly fine except for [line 85](https://github.com/itplusx/bw_captcha/blob/c0e636b53585b5318666e8309cb93483531e382c/Classes/Utility/CaptchaBuilderUtility.php#L85) and that you just added some redundancies (plus creating a minor misbehavior in my eyes). I tested my code with v11+ with only changing that line and it works flawlessly.

Sure, code style is subjective and the codeowner decides what style he want's to have but I just can't shut my mouth when I see unnecessary complexity in code. 

Nevermind. Your repo your rules. 😊

Thanks for your work on this extension and take care
