### ISSUE TITLE
Captcha is always invalid

### ISSUE THREAD

**Issue by MediKathi** [maikschneider/bw_captcha#13]
Hello,

currently I have the problem, that the Captcha is always invalid.

I outputed the compared Captchas wihing via var_dump CaptchaValidator.php (validateCaptcha method).

for some unknown reason the $phrase from the cache is always wrong.

Typo3 v11.5.19 and bw_captcha 2.0.0

**Comment by maikschneider** [comment]
Hey, thanks for the feedback!
That sounds odd, could please test again with v2.0.2 and tell me how you included the form? 
* Have you included multiple instances of a form on a page?
* Do you use the default template?

**Comment by MediKathi** [comment]
Hello,

there are multipe forms on the page for multiple purposes and the template is also modified (not the default template, the partial path of the Captcha.html) is overwritten.

**Comment by maikschneider** [comment]
Hey @MediKathi, thanks for looking into it!
Your fix is kind of a workaround for an error that should not be there in the first place. I think I have a guess of what's going on and just pushed a fix to the development branch. Could you please check it out?

**Comment by maikschneider** [comment]
Yeah, glad to hear this! I just released a bugfix [release 2.0.3](https://github.com/maikschneider/bw_captcha/releases/tag/v2.0.3) and will close your PR since it's more like a workaround. Thank you very much for your effort! :)
