### ISSUE TITLE
Problematic usage of caching framework to store the captchas / missing invalidation

### ISSUE THREAD

**Issue by akiessling** [maikschneider/bw_captcha#19]
Extension Version 2.0.4
TYPO3 10.4.36

While adding the extension to a project, i found some problems regarding the usage and implementation of the caching framework

1. After a successful submit, the used captcha is not removed from cache table. Thus i am able to use the captcha again until it expires. Shouldn't the captcha be invalidated after a successful use? 

2. Cache lifetime
The lifetime of the cache entry is 1 day, set in multiple places when an image is generated. This could IMHO be set to a lower value so you won't spam the database on high-traffic sites and could be moved to the cache backend configuration https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CachingFramework/FrontendsBackends/Index.html#cache-backends

3. To clean up the expired entries, a hint towards the Caching framework garbage collection Scheduler task should be added
And probably the backend needs to be explicitly set until https://forge.typo3.org/issues/98716 is fixed

4. Clearing the sys cache from the toolbar also clears the cache_bwcaptcha table. Hopefully editors don't have the right to do so, but i know admins that regularly hit the clear sys cache button... I'm not sure if specific cache tables can be excluded from sys cache flushing. I thought i read about this some time ago, but can't find anything in the code or the documentation regarding it. Probably that was the cache freezing option.

Dropping the caching framework for the captcha storage is probably the way to go to solve the issues.

**Comment by dev-rke** [comment]
Hi @akiessling ,

from my perspective your observations are correct and i support your proposal to drop the caching framework.

Propably it might make more sense to store the captcha code to a user session?
To ensure there is only one valid captcha per url per user?
User sessions are invalidated automatically after a defined period, so captchas won't be stored forever.
An own database has the downside, that one needs to define a connection between form, captcha code and user session.

Using the user session has the downside, when the user blocks cookies, he might be unable to send a form anymore.

**Comment by dev-rke** [comment]
Currently the captcha code is stored within a cache table:
https://github.com/maikschneider/bw_captcha/blob/development/Classes/Validation/Validator/CaptchaValidator.php#L51

In my opinion it should be stored within the user session as well, as the captcha should be unique per user per url.

**Comment by maikschneider** [comment]
Hey! Good point. I didn't care about invalidation and relied on the garbage collection. Dropping the caching framework makes absolute sense.

Currently not the code, but a captcha ID is stored in the session which points to the code in the cache. If the user blocks cookies, the current implementation doesn't work (I think this is an acceptable risk - visitors doing this will encounter a lot of problems around the web and are certainly familiar to such issues). I have to keep in mind that there could be multiple captcha elements on one page.

I like the idea of saving the code directly in the user session. We could encrypt the code to make it a bit more secure. Do you see any problems by switching to this method?

**Comment by dev-rke** [comment]
Hi @maikschneider ,

we could generate a unique hash based on page id, language id, content element id and form element identifier to exactly address a form element on a page.

But even then: if you open the same form in two browser tabs (sharing the same session) you could enter the code of tab A in tab B and it would validate. But currently i don't see any security problem in this behaviour, because it is not possible to bypass the captcha logic.

I did not understand the benefit of the encryption part. Nobody is able to see the stored data in the user session, because the user session is stored on the server. Only the cookie with a random hash identifier is sent as a cookie to the browser, but the session data itself never leave the server.

**Comment by akiessling** [comment]
> we could generate a unique hash based on page id, language id, content element id and form element identifier to exactly address a form element on a page.

Just a sidenote: I regularly embed forms into extensions like e.g. described in https://sitegeist.de/blog/typo3-blog/typo3-form-framework-formulare-in-eigenen-extensions-nutzen.html so the content element context might not always be a form element. There is also the php api to create forms, but i have not _yet_ used that one so far. 

I also don't see any requirement for encryption. Let's keep it simple :)

**Comment by dev-rke** [comment]
Valid point, never used the native php implementation.
In my opinion we should have an identifier to verify the users location matches the captcha code the user entered.

But it is also hard to define a valid identifier at captcha field build time, as the identifier has to be accessible to all users, so it is not enough to store it in the users session of the user who is generating the captcha field page cache.
Probably you are right and we should follow KISS first.

**Comment by maikschneider** [comment]
Solved in [v3.0.0](https://github.com/maikschneider/bw_captcha/releases/tag/v3.0.0)
