### ISSUE TITLE
Casing mismatch between image and actual captcha

### ISSUE THREAD

**Issue by akiessling** [maikschneider/bw_captcha#20]
Extension Version 2.0.4
TYPO3 10.4.36

With the default settings, i randomly get mismatches between the generated image and the actual text

Example:
![captcha](https://user-images.githubusercontent.com/2895543/218984306-f2a85f02-a6aa-46f1-8e28-a9e1a7d287fc.jpeg)

But the cache_bwcaptcha entry has this value `s:5:"um1QY";`
Entering the uppercase letters does not work, entering the db entry works.

The only adjustments to the default config are these to get a bigger image and remove some problematic characters
```
plugin.tx_bwcaptcha.settings {
    width = 300
    height = 80
    charset = abcdefghjkmnpqrstuvwxyz123456789ABCDEFGHJKLMNPQRSTUVWXYZ
}
```

I don't know if it is a font issue etc, but maybe the comparison should just lowercase/uppercaes everything? Or set the default TypoScript config to only use uppercase characters?

**Comment by maikschneider** [comment]
Oha, that's a strange problem. Does your captcha sometimes display lower case letters? Maybe the font is really broken.. You're not using a custom font, right?

When creating a new version with the new implementation I'll keep an eye on it. 

Regardless of this: With the default configuration of the captcha library the generated images are super tricky to solve - I'm thinking about setting some easier defaults (like only uppercase) for a while. Maybe I'll do this in the next major release.

**Comment by akiessling** [comment]
> Oha, that's a strange problem. Does your captcha sometimes display lower case letters? Maybe the font is really broken.. You're not using a custom font, right?
> 

Nope, only the TS settings above where changed. I only had the error this way, not the other way around. 
It sounded a bit like https://bitbucket.org/blueways/bw_captcha/issues/17/cant-determine-small-or-big-letters-with

> Regardless of this: With the default configuration of the captcha library the generated images are super tricky to solve - I'm thinking about setting some easier defaults (like only uppercase) for a while. Maybe I'll do this in the next major release.

That's how i configured it for now. Should hopefully be safe enough to block an annoying spammer

**Comment by maikschneider** [comment]
Okay. Could be a good idea to test if the problem is in one of the fonts. Maybe you could try only one of the [shipped fonts](https://github.com/maikschneider/bw_captcha/tree/development/Libraries/Captcha/src/Gregwar/Captcha/Font) at a time?

The "M" letter in your example is definitely uppercase. I think the linked issue was more about readability in general.

EDIT: I red you comment again: Are you saying the problem only occurs if the charset setting is set? Not setting anything would not cause the error?

**Comment by akiessling** [comment]
The problem occurred before i removed ambiguous characters. 
I now tested with this setting `fontFiles = EXT:bw_captcha/Libraries/Captcha/src/Gregwar/Captcha/Font/captcha2.ttf` like described in https://bitbucket.org/blueways/bw_captcha/issues/17/cant-determine-small-or-big-letters-with
--> this triggers the bug on every reload (with my USER_INT ;) )

**Comment by akiessling** [comment]
I guess that font should not be used (see https://github.com/Gregwar/Captcha/issues/65) or the check needs to be case insensitive
