### ISSUE TITLE
Missing CacheIdentifier?

### ISSUE THREAD

**Issue by kj-coupling** [maikschneider/bw_captcha#31]
Uncaught TYPO3 Exception: #1298012500: Required argument "cacheIdentifier" is not set for Blueways\BwCaptcha\Controller\CaptchaController->refresh. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown

Hi, I get this error message in my logs. How do i set a cacheIdentifier and where? What am i missing..
I'm currently on TYPY3 11.5.25 - PHP 7.4

Thanks

**Comment by maikschneider** [comment]
Hi @kj-coupling, thanks for the feedback. Which version of the extension are you using?
Have you seen that version [3.0.0](https://github.com/maikschneider/bw_captcha#migration-from-version-2x-to-3x) was released yesterday? This version does not use caching anymore and therefore resolve your problem.

**Comment by kj-coupling** [comment]
I'm using 2.0.3 ..
No i haven't seen it yet, thanks for that. I will check this out.

**Comment by kj-coupling** [comment]
Uncaught TYPO3 Exception: Too few arguments to function Blueways\BwCaptcha\Middleware\Captcha::__construct(), 0 passed

I updated the extension to 3.0.0 and get this new Exception.. Any advice?

**Comment by maikschneider** [comment]
This sounds like Dependency Injection error. Did you flush the cache (`typo3cms cache:flush`)?

**Comment by kj-coupling** [comment]
I flushed all caches again, just to be sure. The error seems to be gone (after reload/flush server memcaches)

I'll let you know if it reappears. Thanks a lot for helping me out so fast.
