### ISSUE TITLE
PHP 8.2 Undefined array key Warning in CaptchaBuilder.php:430

### ISSUE THREAD

**Issue by placeboHummel** [maikschneider/bw_captcha#48]
It seems there's an issue with the bw_captcha extension in TYPO3 v11.5.31 when used with PHP 8.2.8 in development mode. 
Specifically, the problem appears to be related to the dynamic assignment of the "background" variable using:
`$this->background = $bg;` in CaptchaBuilder.php:430

**Comment by maikschneider** [comment]
Hey @placeboHummel, thanks for reporting! 
This is actually [an issue](https://github.com/Gregwar/Captcha/issues/109) of the package [gregwar/captcha](https://github.com/Gregwar/Captcha). I will update the dependency! 

Do you have [this php issue](https://github.com/Gregwar/Captcha/issues/110) as well?

**Comment by maikschneider** [comment]
Could you please test [dev-link-gregwar-captcha](https://github.com/maikschneider/bw_captcha/tree/link-gregwar-captcha) if this resolves your issues?

**Comment by placeboHummel** [comment]
Wow, that was fast! Very much appreciated - works well now!
