### ISSUE TITLE
Creation of dynamic property Gregwar\Captcha\CaptchaBuilder::$background is deprecated

### ISSUE THREAD

**Issue by garbast** [maikschneider/bw_captcha#54]
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: Creation of dynamic property Gregwar\Captcha\CaptchaBuilder::$background is deprecated in /usr/local/apache2/htdocs/fischer/www/vendor/blueways/bw-captcha/Libraries/Captcha/src/Gregwar/Captcha/CaptchaBuilder.php line 430

The property needs to be defined beforehand.

**Comment by maikschneider** [comment]
Hi @garbast, thanks for reporting!
Could you please specify which version of bw_captcha, TYPO3 and PHP you are using?

**Comment by garbast** [comment]
bw_captcha v3.1.0, TYPO3 12.4.9, PHP 8.2.7

**Comment by maikschneider** [comment]
With your setup, you can update to [4.0.2](https://github.com/maikschneider/bw_captcha/releases/tag/v4.0.2). This version should resolve the problem (see #48)

**Comment by garbast** [comment]
Sorry for not checking this first. My composer.json was missing ext-gd which resulted in an older version with composer req. I should have checked this first.

**Comment by garbast** [comment]
After upgrading the captcha worked like a charm. Thanks for the quick response and keep up the good work.
