### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### ISSUE THREAD

**Issue by garbast** [maikschneider/bw_captcha#55]
When opening a form with an included captcha the captcha is shown at first and after a few seconds it gets replace with an broken image icon and the error

```net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)```

Which leads to not being able to solve the captcha.

![image](https://github.com/maikschneider/bw_captcha/assets/5036924/7a8d14b6-38b4-4dee-8336-1a9972da5657)

**Comment by maikschneider** [comment]
Hey, please tell me the versions you are using.
Additionally, which browser are you using, do you have the same issue in another? 
I see that you are logged into the Backend: Does happen when you are not logged in as well?

**Comment by garbast** [comment]
bw_captcha v3.1.0, TYPO3 12.4.9, PHP 8.2.7 with Chrome Version 120.0.6099.129 (Offizieller Build) (64-Bit).

Firefox 103.0.1 (64-Bit) does not complain about the content length

**Comment by garbast** [comment]
The problem only occures on the initial load because the Catcha Middleware only sets the Content-Length if the now parameter isn't set. Now only gets set in the refresh of the captcha. So this behaviour is correct.

I changed from:
```
            $contentLength = floor((strlen($binaryImage) + 2) / 3) * 4;
            $response = $response->withHeader('Content-Length', (string)$contentLength);
```
to: 
```
$response = $response->withHeader('Content-Length', (string)strlen($binaryImage));
```
and the error is gone.

I quite do not get the calculation. The Content-Length should always match the binary values of the response body. So why doing math on the string length at all?

**Comment by maikschneider** [comment]
Ah, okay you're using an old version. This problem looks like #38 (the fix there introduced the problem). In #46 this should have been resolved. Could you please try to update to [4.0.2](https://github.com/maikschneider/bw_captcha/releases/tag/v4.0.2) and test again?

**Comment by garbast** [comment]
Sorry for not checking this first. My composer.json was missing ext-gd which resulted in an older version with composer req. I should have checked this first.
