### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by bh-teufels** [maikschneider/bw_captcha#65]
I currently have the problem that the captcha image is not displayed (broken image icon)

Environment is
PHP 8.2.19
TYPO3 12.4.14
bw_captcha v4.0.4

has anyone had the same error?

**Comment by bh-teufels** [comment]
seems to be fixed with TYPO3 12.4.15

**Comment by ma-gu-16** [comment]
TYPO3 12.4.17 here and bw_captcha 4.0.4    no image.
