### ISSUE TITLE
Storing/reading phrases in session is inconsistent

### ISSUE THREAD

**Issue by yodaXX** [maikschneider/bw_captcha#82]
Kind of a weird issue. I was wondering if anybody has the same problem as me.
Customer reported issues with the captcha on his page, captcha inputs are claimed invalid.

Tried debugging the issue.
The stored session data in Middleware/Captcha seemed fine at first look, until I examined the data in CaptchaValidator.
The previously stored data wasn't there during validation. Was looking into the data from the request (frontend.user, frontend.controller) and the data was inconsistent there too.
Idk why the frontend session is acting that weird but i managed to fix it in my case by relying on the frontend.user attribute from the request object in both Middleware/Captcha and CaptchaValidator.

**Comment by maikschneider** [comment]
Hey @yodaXX , thanks for reporting!
Have you tried dev-main, there is the switch to `frontend.user` (#75)? I haven't released a new version yet.

**Comment by yodaXX** [comment]
Hi, i only tested it with the latest version available from TER yet, forgot to mention.
I guess the mentioned problem will be fixed in the next release, thank you. 👍
