### ISSUE TITLE
Wrong language selection for audio files in v4.2.*

### ISSUE THREAD

**Issue by IvayloIvanov** [maikschneider/bw_captcha#88]
Hello,

after upgrading from 4.1.2 to 4.2.1 the audio files do not match the used language anymore.

Usecase:
* Open an form with the captcha
* The constant audioButton is set to 1
* Klick on the sound icon to play the sound
* In your site config the locale is set to  'de_DE.utf8'

TYPO3 v12.4.23
bw_captcha v4.2.1
Language German

The locale ist set according to the TYPO3 pulldown.
<img width="365" alt="image" src="https://github.com/user-attachments/assets/fb4115b1-b1f1-4984-adb3-73a6b0364851">

Even when I remove the utf8 part the desired audio file isn't playing. The fallback english files are playing.

Thanks and best regards
Ivaylo Kolbinger Ivanov

**Comment by edenlim** [comment]
Hi, I am also having the same problem. 

I was testing around with the vendor folder directly and found out that when i change the code in blueways/bw-captcha/Classes/Middleware/Audio.php from:
$languageCode = $request->getAttribute('language')?->getLocale()->getCountryCode() ?? '';

to:
$languageCode = $request->getAttribute('language')?->getLocale()->getLanguageCode() ?? '';

then the extension works. I'm guessing that Country code is DE and Language code is de, but the extension did not take into account the casing issue, leading it to fall back to english as default

**Comment by maikschneider** [comment]
Hey, thanks for reporting! It's now fixed in [v4.2.2](https://github.com/maikschneider/bw_captcha/releases/tag/4.2.2)
